- name: Play-01
  hosts: web
  tasks:
  - name: Play-01 Task-01
    ansible.builtin.debug:
      msg: "this is task-01 from play-01"

- name: Play-02
  hosts: web
  tasks: 
  - name: Play-02 Task-02
    ansible.builtin.debug:
      msg: "This is task 02 from Play-02"

#Practically one  play can  execute in one playbook. but theritically we can execute n of plays 
