- name: print the variables from file
  hosts: web
  vars_files:
    vars.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}}, triner is {{TRINER}} and duration is {{DURATION}}"