#Filters in Ansible are from Jinja2, and are used for transforming data inside a template expression
# defaulting undefined variables:
#Jinja2 provides a useful ‘default’ filter that is often a better approach to failing if a variable is not defined
- name: demo on filters
  hosts: local
  connection: local
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      #msg: The course is {{ course }}
      msg: The course is {{ course | default('Ansible') }}
# if you execute above playbook we get error undefined variable ( undefined variable. The error was: 'course' is undefined.)
#we can resolve this by declaring default variable


# conver string in to upper case by using "upper" function 
# conver string in to lower case by using "lower" function 
  - name: covert to uppercase
    vars:
      greeting: "Hello Venkat"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: conver to lowercase
    vars:
      greeting: "HELLO VENKAT"
    anssible.builtin.debug:
      msg: "{{ greeting | lower }}"
