- name: command vs shell
  hosts: local
  connection: local
  tasks:
  # - name: execute the command
  #   ansible.builtin.command: ls -ltr > /temp/output.txt

  - name: execute shell
    ansible.builtin.shell: ls -ltr > /temp/output.txt