- name: create ec2 instance and r53 records
  hosts: local
  connection: local

  vars:
    subnet_id: "subnet-054be862e00600196"
    sg_id: "sg-0719181b23b124491"
    image_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend


  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"