- name: create ec2 instance and r53 records
  hosts: local
  connection: local

  vars:
    subnet_id: "subnet-054be862e00600196"
    sg_id: "sg-0719181b23b124491"
    image_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: "vensa.online"

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  # - name: print the output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" 
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results}}"

  - name: create r53 public records for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}" 
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results}}"
    when: item.item == "frontend"